def generate_report(state):

    lines = []

    df = state.dataframe
    quality = state.quality_results or {}
    stats = state.statistical_results or {}
    ml = state.ml_results or {}
    viz = state.visualization_results or {}
    review = state.reviewer_results or {}

    # ==========================================================
    # TITLE
    # ==========================================================

    lines.append("# 🧠 DataMind AI — Automated Data Science Report")
    lines.append("")

    lines.append(
        "This report presents the findings generated by the "
        "DataMind AI multi-agent analysis pipeline."
    )

    lines.append("")

    # ==========================================================
    # 1. DATASET OVERVIEW
    # ==========================================================

    lines.append("## 1. Dataset Overview")
    lines.append("")

    rows = quality.get(
        "rows",
        len(df)
    )

    columns = quality.get(
        "columns",
        len(df.columns)
    )

    lines.append(
        f"The dataset contains **{rows:,} observations** "
        f"and **{columns} variables**."
    )

    numeric_columns = df.select_dtypes(
        include="number"
    ).columns.tolist()

    categorical_columns = df.select_dtypes(
        exclude="number"
    ).columns.tolist()

    lines.append(
        f"The dataset includes **{len(numeric_columns)} numerical "
        f"variables** and **{len(categorical_columns)} "
        f"non-numerical variables**."
    )

    lines.append("")

    # ==========================================================
    # 2. DATA QUALITY
    # ==========================================================

    lines.append("## 2. Data Quality Assessment")
    lines.append("")

    missing_cells = quality.get(
        "missing_cells",
        0
    )

    duplicate_rows = quality.get(
        "duplicate_rows",
        0
    )

    if missing_cells == 0:

        lines.append(
            "The dataset contains **no missing values**, "
            "indicating complete observations across the "
            "available variables."
        )

    else:

        lines.append(
            f"The dataset contains **{missing_cells:,} missing "
            "cells**. These missing observations should be "
            "considered before applying predictive models."
        )

        missing_by_column = quality.get(
            "missing_by_column",
            {}
        )

        if missing_by_column:

            lines.append("")
            lines.append(
                "**Variables affected by missing values:**"
            )

            for column, info in missing_by_column.items():

                count = info.get(
                    "count",
                    0
                )

                percent = info.get(
                    "percent",
                    0
                )

                lines.append(
                    f"- **{column}**: {count:,} missing "
                    f"values ({percent:.2f}%)."
                )

    if duplicate_rows == 0:

        lines.append(
            "No duplicate records were detected."
        )

    else:

        lines.append(
            f"**{duplicate_rows:,} duplicate records** "
            "were detected and should be reviewed."
        )

    constants = quality.get(
        "constant_columns",
        []
    )

    if constants:

        lines.append(
            "Constant variables were detected: "
            + ", ".join(constants)
            + ". These variables provide limited "
              "predictive information."
        )

    else:

        lines.append(
            "No constant variables were detected."
        )

    # Outliers

    outliers = quality.get(
        "outliers",
        {}
    )

    outlier_findings = []

    for column, info in outliers.items():

        count = info.get(
            "iqr_outliers",
            0
        )

        percent = info.get(
            "outlier_percent",
            0
        )

        if count > 0:

            outlier_findings.append(
                (
                    column,
                    count,
                    percent
                )
            )

    if outlier_findings:

        lines.append("")
        lines.append(
            "### Outlier Findings"
        )

        for column, count, percent in outlier_findings:

            lines.append(
                f"- **{column}** contains approximately "
                f"{count:,} potential IQR-based outliers "
                f"({percent:.2f}% of available observations)."
            )

        lines.append(
            "These observations are potential statistical "
            "outliers and should be investigated rather than "
            "automatically removed."
        )

    else:

        lines.append(
            "No IQR-based statistical outliers were detected."
        )

    lines.append("")

    # ==========================================================
    # 3. STATISTICAL ANALYSIS
    # ==========================================================

    lines.append("## 3. Statistical Analysis")
    lines.append("")

    lines.append(
        "The Statistical Agent examined relationships between "
        "numerical variables and assessed their distributional "
        "characteristics."
    )

    lines.append("")

    # Strongest correlations

    top_relationships = stats.get(
        "top_relationships",
        []
    )

    if top_relationships:

        lines.append(
            "### Strongest Correlations"
        )

        for relationship in top_relationships:

            variable_1 = relationship.get(
                "variable_1",
                "Variable 1"
            )

            variable_2 = relationship.get(
                "variable_2",
                "Variable 2"
            )

            correlation = relationship.get(
                "pearson_r",
                0
            )

            absolute_r = abs(
                correlation
            )

            if absolute_r >= 0.70:
                strength = "strong"
            elif absolute_r >= 0.40:
                strength = "moderate"
            else:
                strength = "weak"

            if correlation > 0:
                direction = "positive"
            elif correlation < 0:
                direction = "negative"
            else:
                direction = "negligible"

            lines.append(
                f"- **{variable_1}** and **{variable_2}** "
                f"show a **{strength} {direction} relationship** "
                f"(Pearson r = **{correlation:.3f}**)."
            )

    else:

        lines.append(
            "No meaningful Pearson correlation relationships "
            "were identified."
        )

    lines.append("")

    # Normality

    non_normal = stats.get(
        "non_normal_variables",
        []
    )

    if non_normal:

        lines.append(
            "### Distributional Characteristics"
        )

        lines.append(
            "The following variables were flagged as potentially "
            "non-normal at the 0.05 significance level:"
        )

        for variable in non_normal:

            lines.append(
                f"- **{variable}**"
            )

        lines.append(
            "For statistical modelling, transformations or "
            "non-parametric methods may be considered where "
            "appropriate."
        )

    else:

        lines.append(
            "The tested numerical variables were not flagged "
            "as significantly non-normal at the 0.05 level."
        )

    lines.append("")

    # ==========================================================
    # 4. MACHINE LEARNING
    # ==========================================================

    lines.append(
        "## 4. Machine Learning Analysis"
    )

    lines.append("")

    ml_status = ml.get(
        "status",
        ""
    )

    if ml_status == "OK":

        problem_type = ml.get(
            "problem_type",
            "unknown"
        )

        target = ml.get(
            "target",
            "not specified"
        )

        best_model = ml.get(
            "best_model",
            "not identified"
        )

        rows_used = ml.get(
            "rows_used",
            0
        )

        lines.append(
            f"The ML Agent identified the task as a "
            f"**{problem_type}** problem."
        )

        lines.append(
            f"The selected prediction target is "
            f"**{target}**."
        )

        lines.append(
            f"The modelling process used **{rows_used:,} "
            "usable observations** after target validation."
        )

        lines.append(
            f"Among the evaluated baseline models, "
            f"**{best_model}** achieved the best performance "
            f"according to the selected evaluation criterion."
        )

        lines.append("")

        models = ml.get(
            "models",
            {}
        )

        if models:

            lines.append(
                "### Model Comparison"
            )

            if problem_type == "classification":

                for model_name, metrics in models.items():

                    accuracy = metrics.get(
                        "Accuracy",
                        0
                    )

                    f1 = metrics.get(
                        "F1",
                        0
                    )

                    lines.append(
                        f"- **{model_name}** — "
                        f"Accuracy: **{accuracy:.4f}**, "
                        f"Weighted F1: **{f1:.4f}**."
                    )

            else:

                for model_name, metrics in models.items():

                    mae = metrics.get(
                        "MAE",
                        0
                    )

                    rmse = metrics.get(
                        "RMSE",
                        0
                    )

                    r2 = metrics.get(
                        "R2",
                        0
                    )

                    lines.append(
                        f"- **{model_name}** — "
                        f"MAE: **{mae:.4f}**, "
                        f"RMSE: **{rmse:.4f}**, "
                        f"R²: **{r2:.4f}**."
                    )

    else:

        message = ml.get(
            "message",
            "A suitable machine-learning analysis "
            "could not be completed."
        )

        lines.append(
            f"Machine-learning analysis was not completed: "
            f"{message}"
        )

    lines.append("")

    # ==========================================================
    # 5. VISUALIZATION
    # ==========================================================

    lines.append(
        "## 5. Visualization Summary"
    )

    lines.append("")

    total_figures = viz.get(
        "total_figures",
        len(
            viz.get(
                "figures",
                []
            )
        )
    )

    if total_figures > 0:

        lines.append(
            f"The Visualization Agent generated "
            f"**{total_figures} analytical visualizations** "
            "to support interpretation of the dataset."
        )

        lines.append(
            "These visualizations include distribution analysis, "
            "correlation structure, outlier inspection and, "
            "where available, machine-learning performance."
        )

    else:

        lines.append(
            "No analytical visualizations were generated."
        )

    lines.append("")

    # ==========================================================
    # 6. RELIABILITY REVIEW
    # ==========================================================

    lines.append(
        "## 6. Reliability Review"
    )

    lines.append("")

    reliability = review.get(
        "reliability",
        "UNKNOWN"
    )

    reason = review.get(
        "reason",
        ""
    )

    lines.append(
        f"Overall analysis reliability assessment: "
        f"**{reliability}**."
    )

    if reason:

        lines.append(
            reason
        )

    warnings = review.get(
        "warnings",
        []
    )

    if warnings:

        lines.append("")
        lines.append(
            "### Important Considerations"
        )

        for warning in warnings:

            lines.append(
                f"- {warning}"
            )

    lines.append("")

    # ==========================================================
    # 7. KEY INSIGHTS
    # ==========================================================

    lines.append(
        "## 7. Key Insights"
    )

    lines.append("")

    # Quality insight

    if missing_cells == 0 and duplicate_rows == 0:

        lines.append(
            "1. **Data quality is generally clean**, with no "
            "missing cells or duplicate records detected."
        )

    else:

        lines.append(
            "1. **Data quality requires attention** because "
            "missing or duplicate records were identified."
        )

    # Correlation insight

    if top_relationships:

        strongest = top_relationships[0]

        lines.append(
            f"2. The strongest detected numerical relationship "
            f"is between **{strongest.get('variable_1')}** and "
            f"**{strongest.get('variable_2')}**, with Pearson "
            f"r = **{strongest.get('pearson_r'):.3f}**."
        )

    else:

        lines.append(
            "2. No strong numerical relationships were identified "
            "by the correlation analysis."
        )

    # Outlier insight

    if outlier_findings:

        highest_outlier = max(
            outlier_findings,
            key=lambda x: x[2]
        )

        lines.append(
            f"3. **{highest_outlier[0]}** has the highest "
            f"proportion of potential IQR-based outliers "
            f"({highest_outlier[2]:.2f}%)."
        )

    else:

        lines.append(
            "3. No major IQR-based outlier patterns were detected."
        )

    # ML insight

    if ml_status == "OK":

        lines.append(
            f"4. The best baseline ML model was "
            f"**{ml.get('best_model', 'not identified')}** "
            f"for the **{ml.get('problem_type', 'unknown')}** task."
        )

    else:

        lines.append(
            "4. A reliable baseline ML model could not be "
            "established from the available target information."
        )

    # ==========================================================
    # 8. RECOMMENDATIONS
    # ==========================================================

    lines.append("")
    lines.append(
        "## 8. Recommendations"
    )

    lines.append("")

    if missing_cells > 0:

        lines.append(
            "- Investigate the mechanism of missingness and "
            "apply an appropriate imputation strategy."
        )

    if outlier_findings:

        lines.append(
            "- Investigate potential outliers using domain "
            "knowledge before deciding whether to remove, "
            "transform or retain them."
        )

    if top_relationships:

        lines.append(
            "- Consider the strongest correlated variables "
            "during feature engineering and predictive modelling, "
            "while avoiding causal interpretation of correlation."
        )

    if ml_status == "OK":

        lines.append(
            "- Apply cross-validation and hyperparameter tuning "
            "before using the selected model for production or "
            "research-grade prediction."
        )

    lines.append(
        "- Combine statistical findings, visual evidence and "
        "domain knowledge before making final decisions."
    )

    lines.append("")

    lines.append(
        "---"
    )

    lines.append(
        "Generated automatically by **DataMind AI — "
        "Autonomous Multi-Agent Data Science Assistant**."
    )

    return "\n".join(lines)
